//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam__Info
    {
        public int Id { get; set; }
        public string Exam_Name { get; set; }
        public Nullable<int> RoomNo { get; set; }
        public string Teacher_Name { get; set; }
    }
}
